### ISSUE TITLE
[suggestion]: click on Journal Link opens window, that's already minimized

### ISSUE THREAD

**Issue by PhilMC157** [saif-ellafi/foundryvtt-window-controls#11]
I've been using your great tool for awhile now and I came across to minor issues in my latest sessions.
Issue 1.)
Situation: I have, let's say, two journals open and minimized in the taskbar.  an entry/link in journal_1 referes to journal_2. If I click on the link to open up journal_2 (miminized in taskbar), it won't come up. therefore I have to check where my journal_2 is in the taskbar and doubleclick it to open it. which is ok, when u have only 2 or 3 windows minimized. with more minimzed journals it get's tricky and costs time when I need the journal entry real fast. 
Suggestion: click on a journal link opens up the referenced minimized journal

Issue 2.)
Situation: On my computer screen, after 5 or 6 entries the taskbar is full and any additonal windows get minimized **behind** the current taskbar. 
Suggestion: is there a way to extend the taskbar below (if it's pinned on top)?

Thanks in advance and I hope it made sense what I was trying to explain.
-Philip

**Comment by saif-ellafi** [comment]
Hi @PhilMC157 - thank you for the real-game based feedback!
1. Regarding bug number 1, will take a look as soon as possible.
2. Regarding full entries, they should definitely not end up **behind**, on overflow, new minimized windows should have minimization functionality disable and be minimized floating

In the future, maybe we can do something better about overflows

**Comment by saif-ellafi** [comment]
These issues you reported are very tricky for me to reproduce, something else must be going on, or you are on an outdated version of Window Controls. Could you verify? also which System are you playing? to discard system conflicts...

**Comment by PhilMC157** [comment]
I updated to your latest version (1.3.5). The overflow issue has slightly changed. Now the window floats on top of the scene navigtion. 
And thanks for looking into Issue 1 as well.

![FVTT_Windows_Overflow](https://user-images.githubusercontent.com/70864790/144976393-da21218f-634f-4bc6-8236-6ea03ac17cb9.JPG)

**Comment by saif-ellafi** [comment]
@PhilMC157 - I see you updated to the latest version, so does issue number 1 still happen?? can you replicate it?

Regarding the floating windows, I think for now it is a good enough to survive no? we can focus on issue 1.

**Comment by PhilMC157** [comment]
Issue 1 still happens. Just to be sure, I deactivated your module to see how it works in core and it has the same behavior. 
Issue 2 rarely happens in my games anyways, because I don't use too many floating windows. Just by coincidence I stumpled upon the window overflow issue. Good enough to survive. ;)

**Comment by saif-ellafi** [comment]
Thank you @PhilMC157 - 
if issue number one happens on Core Foundry, I am glad it is not me :D but we should still report the bug on Foundry VTT!
If issue number two, floating windows when "Overflowing" is good enough for now and there is nothing that impeds productivity or broken, there for now we are good! 
Closing the issue for now! Let me know if there are any other points or questions.
