### ISSUE TITLE
problems with midi and templates

### ISSUE THREAD

**Issue by rinnocenti** [saif-ellafi/foundryvtt-window-controls#13]
![image](https://user-images.githubusercontent.com/3178127/146853457-f392cb2c-e7b5-48b6-9ca3-eba7303ad90d.png)
when I put the active module I have problems to use MIDI when some action requires a template and I have the active module.

when I try to make an action using a template it causes an error and doesn't evolve correctly.

**Comment by saif-ellafi** [comment]
Hello @rinnocenti,  thank you for bug reporting this. Could you please help me with the modules you are using? I am not familiar with the DnD world, so I am not sure what "MIDI" is, thank you!

**Comment by rinnocenti** [comment]
https://gitlab.com/tposney/midi-qol

Midi is the module of automation in DND5e.

**Comment by saif-ellafi** [comment]
Can you guide me a bit into reproducing this issue? what is an action using a template and how can I test it?

**Comment by saif-ellafi** [comment]
I think I could reproduce it, apparently only happening on Foundry V9

**Comment by saif-ellafi** [comment]
Thank you for reporting this @rinnocenti - it was a bit of a shady bug but hopefully it is now solved in 1.5.3. Let me know otherwise :)
