### ISSUE TITLE
Possible compatibility issue with Forien's Quest Log

### ISSUE THREAD

**Issue by Kev1112005** [saif-ellafi/foundryvtt-window-controls#14]
Module Version: v1.5.3

Describe the bug:
When I open the Forien's Quest Log (v0.7.9) quest tracker, I am unable to minimize or close the quest tracker if Window Controls is enabled. If I disable Window Controls this issue does not persist.

Go to Journal Notes button on the left side of the menu.
Click on Quest Tracker button.
Attempt to close/minimize the window.

Expected behavior:
I expect that the window would minimize or close, like other windows. Instead, they stay stuck, unable to minimize or close the window. This issue persists between logins. 

Screenshots
![image](https://user-images.githubusercontent.com/30413531/147174636-9c175000-ab76-4aa5-89c7-17f603b04e88.png)

Browser: Brave Browser, v1.33.106
Foundry Version: v0.8.9
Game System: DnD5e v1.5.6
Link to Forien's Quest Log GitHub: https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log

**Comment by saif-ellafi** [comment]
Hi @Kev1112005 
I am not planning on supporting 0.8.x anytime soon.
When possible, please confirm if this is still valid on V9.

**Comment by JordanRR** [comment]
I have the same problem, but I'm also on 0.8.9.

**Comment by NutritiousCookie** [comment]
This is a problem for me on v9

**Comment by saif-ellafi** [comment]
Hey all @JordanRR @NutritiousCookie @Kev1112005 - Window Controls 1.6.3 should work with Forien! Could anyone please confirm?

**Comment by JordanRR** [comment]
> Hey all @JordanRR @NutritiousCookie @Kev1112005 - Window Controls 1.6.3 should work with Forien! Could anyone please confirm?

I still have the same problem, I'm on Foundry 0.8.9.

**Comment by saif-ellafi** [comment]
Ah, I am very sorry @JordanRR - Installing 0.8.9 with an old version of a module, to support both and old Foundry and an external module simultaneously is too much for the moment :) Will update to indicate that it is only for V9+

**Comment by JordanRR** [comment]
> 

No problem. Thanks!
