### ISSUE TITLE
Remembered pinned windows don't update properly

### ISSUE THREAD

**Issue by MikauSchekzen** [saif-ellafi/foundryvtt-window-controls#16]
**Operating System** Arch Linux 64-bit
**Browsers tested** Chromium and Firefox
**Modules active** Just Window Controls

Steps to reproduce (with the DnD5e system):

1. Create an actor, if you don't have one already.
2. Make sure 'Remember Pinned Windows' is enabled in Window Controls' options.
3. Pin (and minimize) the actor.
4. Refresh the page.
5. Open the actor from the pinned windows list.
6. Change an ability score (such as Strength) to something that would also change the modifier.

The modifier doesn't change with the actor's new ability score, when it should have.

This seems to only be an issue for remembered windows. Just minimizing a window and opening it later in the current session doesn't cause this issue.

**Comment by saif-ellafi** [comment]
Thank you for reporting this @MikauSchekzen - This is awesome. I don't do anything strange just reopen the actor :D
Mysteries, mysteries...

**Comment by saif-ellafi** [comment]
Thank you @MikauSchekzen for bringing this bug to me. I would have never found it on my own.
This should be fixed on 1.7.8 - Please let me know if otherwise.

**Comment by MikauSchekzen** [comment]
Oh, that was quick. I'll keep an eye out. :)

**Comment by MikauSchekzen** [comment]
Alright, seems to be fixed with 1.7.8. Cheers!
