### ISSUE TITLE
Incompatibility with Forien's Quest Log

### ISSUE THREAD

**Issue by XtraButtery** [saif-ellafi/foundryvtt-window-controls#19]
```
Foundry VTT Version 9 (Build 255)
Running on ForgeVTT
FoundryVTT Window Controls: 1.9.2
Forien's Quest Log: 0.7.9
```

This issue appears similar to the previous issue #14 

When opening Forien's Quest Log the main window cannot be moved or resized while Window Controls is installed.

The Quest Log itself otherwise remains functional, however as it cannot be properly interacted with it is impossible to adjust it's z position over other windows or to reposition it away from the absolute centre of the screen making it impossible to use alongside any other open windows.

**Comment by saif-ellafi** [comment]
Hi @XtraButtery - appreciated the patience. This is now fixed in 1.9.3
Have fun and let me know if you find anything else :)
