### ISSUE TITLE
Option to disable click+drag of minimized app, or use for rearranging apps

### ISSUE THREAD

**Issue by flamewave000** [saif-ellafi/foundryvtt-window-controls#2]
Currently the minimized apps can still be dragged off of the bar. It would be nice if there was an option to disable this interaction to prevent accidental drags while moving around the scene.

As an extension of that, it would be neat if one could rearrange the app windows on the bar by dragging the minimized app around.

**Comment by saif-ellafi** [comment]
Thank you @flamewave000 I was a bit gone for a while :D 

I have tried this in the past but it lead to very odd problems, as it needs some strong rule overriding of Foundry's windows behavior. In the old release it was "horizontally" fixed, but it had a few issues.

It is certainly something that I would like to figure out how to do right.

**Comment by saif-ellafi** [comment]
@flamewave000 ! I have now implemented the windows so they are no longer moveable. Re-arranging will likely be more difficult

**Comment by saif-ellafi** [comment]
This is now fulfilled :-) - Auto arranging minimized windows released in 1.3.x series
