### ISSUE TITLE
Window Sticking / opening issue

### ISSUE THREAD

**Issue by roguedevjake** [saif-ellafi/foundryvtt-window-controls#20]
Foundry: v9.255
Ruleset: PF2e v3.7.2
Modules: Clean world, only window controls active

Issue: When an actor, item or journal entry is opened initially it works as expected. When opened a second time and whilst the initial actor/item/journal is open the object window will freeze, and be unable to be moved by the title bar. 
If you open the same item a third time it will return to being able to be moved, and if you open a fourth back to being immobile (repeating)

**Comment by saif-ellafi** [comment]
Hi @roguedevjake - appreciated the patience and reporting this problem. This is now fixed in 1.9.3
Have fun and let me know if you find anything else :)
