### ISSUE TITLE
[SUGGESTION] Increase default size for cssMinimizedSize or add variable option

### ISSUE THREAD

**Issue by Shuggaloaf** [saif-ellafi/foundryvtt-window-controls#3]
Minimized token character sheets are indistinguishable at current width. It's always been a bit tight but when you factor in having the word "[Token]" and adding the new restore button and any other mod buttons (for example I use CUB's hide name functions which adds a button) All you can see is the word [Token].

_Preferably_, the minimized windows would dynamically resize to fit the title (up to a reasonable length). However I understand that may be a lot of work. As a quick-fix/work-around suggest increasing cssMinimizedSize to a larger width (examples below)
`default size`
<img src="https://user-images.githubusercontent.com/79543184/131713040-958f27e3-2d6e-4c76-b521-e3cc7a340e19.png" width="50%"/>
`static cssMinimizedSize = 200;`
<img src="https://user-images.githubusercontent.com/79543184/131714433-aa3c8d44-c666-47dc-b37a-a9476ce45cb0.png" width="65%"/>
`static cssMinimizedSize = 250;`
<img src="https://user-images.githubusercontent.com/79543184/131714584-1d4915b9-d7c1-482b-926c-92b4a06d5661.png" width="80%"/>

I understand a larger static size could take up unnecessary space, however without increasing it, it can potentially be impossible to tell what's what. Perhaps a middle ground between a dynamic resize solution and a rigid default size would be to add a box/slider/drop-down to settings to allow the user to choose what works for them.

**Comment by saif-ellafi** [comment]
Another option could be to remove the [Token] keyword of token tabs. As it seems really of little value to me. Maybe change it with [T] or something alike?

**Comment by Shuggaloaf** [comment]
That's a good idea and I would say implement it because I agree, [Token] isn't very useful. 

BUT I still think there needs to be a bit of a width increase as well. Even with your solution, at the current default width (and using a "commoner" token as an example) you would still only see something like `[T] Comm`. Which is definitely better than it is currently, but a few more pixels would help. 

I've been running at ` static cssMinimizedSize = 200;` and haven't looked back. I've never an issue with the top bar filling up or with names being cut off. But with your `[T]` solution you may even be able to drop that down a bit to 180 or so.

**Comment by saif-ellafi** [comment]
Thank you @Shuggaloaf - The idea was quite straight forward to do so it is now released :) Instead of [Token] it will show a symbol `~` to remind it has something different at least and takes less space than [T].

I have tried with different `cssMinimizedSize` levels but I found some challenges when it comes to calculating properly the length of the "background bar". Will check it out a bit more but glad to hear you have found a value that works for you. Also I have released various hotfixes so I suggest upgrading :)

Will Keep this open as to consider how flexible can the minimized size be.

**Comment by Shuggaloaf** [comment]
Wow that was super fast! The `~` being used instead of the `[T]` seems like a good idea and saves a char or 2 in width. With this it may not even be necessary to expand minSize. 

And yeah as far as the background bar, I completely forgot about that as I had disabled it. Possibly due to the same issues you were running into. 

I'll definitely look into updating within the next day or 2. Thanks for working on it and I'll give you my opinion on the size in a day or 2 as well (for whatever it's worth ;-) )

**Comment by Shuggaloaf** [comment]
Just wanted to give you an update that I'm still running 0.8.8 so it won't allow me to update since min version is 0.8.9. 
I will look into updating core Foundry and if/once I do, will get back here with some feedback.
