### ISSUE TITLE
Issue with Tokenizer

### ISSUE THREAD

**Issue by horusofoz** [saif-ellafi/foundryvtt-window-controls#34]
There is an conflict with [Tokenizer](https://github.com/MrPrimate/tokenizer). When Window Control is enabled, the Tokenizer window is too small to fit the content.

With Window Controls enabled.
![image](https://github.com/saif-ellafi/foundryvtt-window-controls/assets/3202339/acc7c554-d7f1-4bf9-803e-9c26bd8ed338)

With Window Controls disabled.
![image](https://github.com/saif-ellafi/foundryvtt-window-controls/assets/3202339/fc8cd3d9-39e4-42ba-a10a-fd330d8a07be)

Experienced while using Foundry locally on Windows 10 Pro (10.0.19045).

Foundry Version: 11 Build 302
System Version: D&D5E 2.2.1
Tokenizer Version: 4.2.1
Window Controls Version: 1.11.2

[Reported to Tokenizer](https://github.com/MrPrimate/tokenizer/issues/136).

**Comment by saif-ellafi** [comment]
Never experienced the too small thing - but defeinitely wanted to fix the double pasting. I need to detect whether tokenizer is active and give it priority
