### ISSUE TITLE
Trying to support Window Controls in my Upcoming Module Window Tabs

### ISSUE THREAD

**Issue by mouse0270** [saif-ellafi/foundryvtt-window-controls#36]
I am trying to add support for Window Controls in my Upcoming Module Window Tabs. 

Window Tabs adds Tab like grouping to Foundry windows. Best shown than described.

![image](https://github.com/saif-ellafi/foundryvtt-window-controls/assets/564874/995aa807-64e3-47cc-a549-03c2d5e77b66)

The problem is, when I installed Window Controls to add compatibility, I realized that when you minimize the window that all my tabs are removed. After some research, I found that its because you use `.text` [LINE](https://github.com/saif-ellafi/foundryvtt-window-controls/blob/dbaec01d4c83275de7228a716157980b57f26edc/windowcontrols.js#L290C5-L290C5) to set the title of the window on minimize and maximize. The problem is, I store the tabs in the `h4.window-title` so your module basically wipes out all of my tabs.

I was curious if you had any ideas on how we could get our modules to work together?

**Comment by mouse0270** [comment]
Actually, maybe ignore this, I should be able to move my tabs into a new div, this will keep the ui more standard for your module.

**Comment by mouse0270** [comment]
So I got the deleting my tabs resolved, minimizing never deletes the tabs, but everything else between our modules just breaks. haha. I am going to see if I can resolve them...

**Comment by saif-ellafi** [comment]
Hey @mouse0270 - sorry for the late reply. Let me know if you need any help, although honestly I am just keeping the modules alive, not working too much on them
