### ISSUE TITLE
Persistent Top/Bottom Bar doesn't work

### ISSUE THREAD

**Issue by PhilMC157** [saif-ellafi/foundryvtt-window-controls#6]
Hello JeansenVaars,
first of all, thank you for the great tool u wrote for FVTT.  
Everything works for me, except the "Persistent Top or Bottom Bar". 
When I double click or minimize any sheet, it just disappears.  
Using FVTT 0.8.9
Window Controls v1.2.0

- Philip

**Comment by saif-ellafi** [comment]
Hello @PhilMC157 Thank you for the kudos! Could you share which System are you testing with? It is likely an issue with some specific system. If you have any other worlds or system to test with, would be appreciated the information.

**Comment by saif-ellafi** [comment]
I have found a bug in the module that could be causing this, but it could also be there other reason.

**Comment by saif-ellafi** [comment]
OK, the bug I found is related to Windows that have strange characters in the names, like parenthesis or brackets, cause an issue in Persistent mode

**Comment by saif-ellafi** [comment]
I have released 1.2.1 with such Fix now.

**Comment by PhilMC157** [comment]
Whatever u did, it is working now. Many thanks.
OS: Win10
Game System: Call of Cthulhu

**Comment by saif-ellafi** [comment]
Glad to hear! Express customer service :D have fun

**Comment by PhilMC157** [comment]
yes, 100% express service! highly appreciated.
